//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalleOrden
    {
        public int idOrden { get; set; }
        public int idDoctor { get; set; }
        public Nullable<decimal> precioUnidad { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> cantidadTotal { get; set; }
        public Nullable<System.DateTime> fechaOrden { get; set; }
    
        public virtual tb_Doctor tb_Doctor { get; set; }
        public virtual tb_OrdenExt tb_OrdenExt { get; set; }
    }
}
