//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Doctor()
        {
            this.Review = new HashSet<Review>();
            this.tb_detalleOrden = new HashSet<tb_detalleOrden>();
            this.tb_ListaDeseos = new HashSet<tb_ListaDeseos>();
            this.tb_ListaDeseosExt = new HashSet<tb_ListaDeseosExt>();
            this.tb_VistaReciente = new HashSet<tb_VistaReciente>();
        }
    
        public int idDoctor { get; set; }
        public string nomDoctor { get; set; }
        [RegularExpression("[0-9]{8}", ErrorMessage = "DNI Invalido")]
        public string dniDoctor { get; set; }
        [RegularExpression("[0-9]{6}", ErrorMessage = "CMP Invalido")]
        public string cmpDoctor { get; set; }
        public int idCategoria { get; set; }
        public int id_Horario { get; set; }
        public string dirDoctor { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public string telDoctor { get; set; }
        [EmailAddress(ErrorMessage = "Correo inválido ")]
        public string emailDoctor { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> PrecioAnterior { get; set; }
        public string ImageURL { get; set; }
        public System.Web.HttpPostedFileBase ImageFile { get; set; }
        public string TextoAlternativo { get; set; }
        public string caracteristica1 { get; set; }
        public string caracteristica2 { get; set; }
        public string caracteristica3 { get; set; }
        public string caracteristica4 { get; set; }
        public string caracteristica5 { get; set; }
        public Nullable<bool> Placa { get; set; }
        public string TituloOferta { get; set; }
        public string ClaseDistintaOferta { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public string nota { get; set; }
        public Nullable<bool> agregarCarro { get; set; }
        public string caracteristica6 { get; set; }
        public string caracteristica7 { get; set; }
        public string caracteristica8 { get; set; }
        public string porc1 { get; set; }
        public string porc2 { get; set; }
        public string porc3 { get; set; }
        public string porc4 { get; set; }
        public string idUser { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
        public virtual tb_Categoria tb_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalleOrden> tb_detalleOrden { get; set; }
        public virtual tb_Distrito tb_Distrito { get; set; }
        public virtual tb_Horario tb_Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ListaDeseos> tb_ListaDeseos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ListaDeseosExt> tb_ListaDeseosExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_VistaReciente> tb_VistaReciente { get; set; }
    }
}
