//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Pago()
        {
            this.tb_Orden = new HashSet<tb_Orden>();
            this.tb_OrdenExt = new HashSet<tb_OrdenExt>();
        }
    
        public int idPago { get; set; }
        public int idTipoPago { get; set; }
        public Nullable<decimal> MontoCrediyo { get; set; }
        public Nullable<decimal> CantidadDebito { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Orden> tb_Orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrdenExt> tb_OrdenExt { get; set; }
        public virtual tb_TipoPago tb_TipoPago { get; set; }
    }
}
